development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: hogwarts_app_development
  pool: 5
  
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: hogwarts_app_test
  pool: 5
  
