
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: HarryPorter_development
  pool: 5

 
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: HarryPorter_test
  pool: 5
  
