
ravenclaw = House.create(name: "Ravenclaw")
hufflepuff = House.create(name: "Hufflepuff")
slytherin = House.create(name: "Slytherin")
gryffindor = House.create(name: "Gryffindor")



harry = gryffindor.students.create(first_name: "Harry", last_name: "Potter", grade: 7, gender: "male")
hermione = gryffindor.students.create(first_name: "Hermione", last_name: "Granger", grade: 7, gender: "female")
draco = slytherin.students.create(first_name: "Draco", last_name: "Malfoy", grade: 7, gender: "male")
goyle = slytherin.students.create(first_name: "Gregory", last_name: "Goyle", grade: 7, gender: "male")
cedric = hufflepuff.students.create(first_name: "Cedric", last_name: "Diggory", grade: 7, gender: "male")
susan = hufflepuff.students.create(first_name: "Susan", last_name: "Bones", grade: 3, gender: "female")
luna = ravenclaw.students.create(first_name: "Luna", last_name: "Lovegood", grade: 6, gender: "female")
cho = ravenclaw.students.create(first_name: "Cho", last_name: "Chang", grade: 6, gender: "female")

Professor.create(first_name: "Argus", last_name: "Filch")
Professor.create(first_name: "Filius", last_name: "Flitwick")
Professor.create(first_name: "Gilderoy", last_name: "Lockhart")
Professor.create(first_name: "Minerva", last_name: "McGonagall")
Professor.create(first_name: "Poppy", last_name: "Pomfrey")
Professor.create(first_name: "Quirinus", last_name: "Quirrell")
Professor.create(first_name: "Horace", last_name: "Slughorn")
Professor.create(first_name: "Pomona", last_name: "Sprout")
Professor.create(first_name: "Sybill", last_name: "Trelawney")

dada = Lecture.create(name: "Defence Against the Dark Arts", location: "West Wing")
trans = Lecture.create(name: "Transfiguration", location: "East Wing")
potions = Lecture.create(name: "Potions", location: "South Wing")
muggle = Lecture.create(name: "Muggle Studies", location: "North Wing")
creatures = Lecture.create(name: "Care of Magical Creatures", location: "South Wing")

creatures.sections.create(time: "Wednesday, 3 PM")
creatures.sections.create(time: "Thursday, 7 PM")
dada.sections.create(time: "Friday, 11 AM")
dada.sections.create(time: "Monday, 10 AM")
muggle.sections.create(time: "Monday, 3 PM")
muggle.sections.create(time: "Tuesday, 9 PM")
potions.sections.create(time: "Tuesday, 4 PM")
potions.sections.create(time: "Thursday, 1 PM")
trans.sections.create(time: "Tuesday, 9 AM")
trans.sections.create(time: "Friday, 8 AM")

# Spell.create(name: "Accio")
# Spell.create(name: "Expecto Patronum")
# Spell.create(name: "Erecto")
# Spell.create(name: "Expelliarmus")
# Spell.create(name: "Morsmordre")