# House.create(name: 'Gryffindor')
# House.create(name: 'Ravenclaw')
# House.create(name: 'Hufflepuff')
# House.create(name: 'Slytherin')

# Professor.create(name: 'McGonigal')
# Professor.create(name: 'Flitwick')
# Professor.create(name: 'Trelawney')
# Professor.create(name: 'Sprout')
# Professor.create(name: 'Snape')
# Professor.create(name: 'Slughorn')
# Professor.create(name: 'Binns')
# Professor.create(name: 'Dumbledore')

Lecture.create(weekday: 'Monday', topic: 'Transfiguration', student: 1, professor: 1)