House.create(name: 'Gryffindor')
House.create(name: 'Ravenclaw')
House.create(name: 'Hufflepuff')
House.create(name: 'Slytherin')

Professor.create(name: 'McGonigal')
Professor.create(name: 'Flitwick')
Professor.create(name: 'Trelawney')

Student.create(name: "Tom")
Student.create(name: "Dave")
Student.create(name: "Steve")
Student.create(name: "George")
Student.create(name: "Mary")
Student.create(name: "Sue")
Student.create(name: "Ellen")
Student.create(name: "Julie")
Student.create(name: "Rebecca")
Student.create(name: "Cori")

Lecture.create(topic: "Flying", professor_id: 1)
Lecture.create(topic: "Running", professor_id: 2)
Lecture.create(topic: "Sinking", professor_id: 3)
Lecture.create(topic: "Swimming", professor_id: 1)
Lecture.create(topic: "Walking", professor_id: 2)
Lecture.create(topic: "Skipping", professor_id: 3)

